install: skip
script: skip
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_ACCESS_SECRET
  bucket: meaqua.icu
  region: ap-northeast-1
after_deploy:
  - "curl -X POST \"https://api.cloudflare.com/client/v4/zones/023e105f4ecef8ad9ca31a8372d0c353/purge_cache\" -H \"X-Auth-Email: $CLOUDFLARE_EMAIL\" -H \"X-Auth-Key: $CLOUDFLARE_KEY\" -H \"Content-Type: application/json\" --data '{\"purge_everything\":true}' "
